"""add scheduler_jobs

Revision ID: 99d3c25dbacc
Revises: 1
Create Date: 2026-02-23 21:35:28.751098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d3c25dbacc'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_schedule', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('events', 'module',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('events', 'object_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('events', 'event',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'information',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'information',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'event',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('events', 'object_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('events', 'module',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.drop_table('scheduler_jobs')
    # ### end Alembic commands ###
