repos:
- repo: local
  hooks:
    - id: mypy-hook
      name: Custom mypy hook
      entry: bash .githooks/mypy
      language: system
      types: [python]
    - id: ruff-hook
      name: Custom ruff hook
      entry: bash .githooks/ruff
      language: system
      types: [python]
    - id: rde-ddd-linter
      name: RDE DDD Linter
      entry: python openvair/requirements_linter/precommit_script.py
      language: python
      files: ^(docs/reference/modules/|openvair/modules/)
      pass_filenames: false
      additional_dependencies: ['pyyaml', 'pydantic']
